### ISSUE TITLE
Unhandled exception when template file is empty

### ISSUE THREAD

**Issue by jscruz** [Skyscanner/cfripper#101]
Hi, 

I found a minor issue when running cfripper with a list of files. I had a blank file in that list and there was an exception. The exception helped to understand something was wrong but it would be good if cfripper check the validity of the CF file first before throwing an exception.

Please find the steps to reproduce below:

## Steps to reproduce:
Create a blank file:
```shell
touch example.yml
```
Execute cfripper:
```shell
cfripper example.yml
```
Exception is raised:
```shell
Analysing example.yml...
Unhandled exception raised, please create an issue wit the error message at https://github.com/Skyscanner/cfripper/issues
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cfripper/cli.py", line 151, in cli
    process_template(template=template, resolve_parameters=resolve_parameters, **kwargs)
  File "/usr/lib/python3.8/site-packages/cfripper/cli.py", line 90, in process_template
    cfmodel = get_cfmodel(template)
  File "/usr/lib/python3.8/site-packages/cfripper/cli.py", line 39, in get_cfmodel
    cfmodel = pycfmodel.parse(template)
  File "/usr/lib/python3.8/site-packages/pycfmodel/__init__.py", line 19, in parse
    return CFModel(**template)
TypeError: ModelMetaclass object argument after ** must be a mapping, not NoneType
```
I think it should be great if cfripper handles the error outputting a message like:

```shell
Analysing example.yml...
example.yml is not a valid template.
```

Thanks!

**Comment by jsoucheiron** [comment]
Makes sense, we'll fix it, thanks!
