### ISSUE TITLE
Could not parse JSON template

### ISSUE THREAD

**Issue by krouser** [Skyscanner/cfripper#131]
Could not parse JSON template
Traceback (most recent call last):
  File "/opt/Skyscanner/cfripper/cfripper/model/utils.py", line 74, in convert_json_or_yaml_to_dict
    file_content = to_json(file_content)
  File "/usr/local/lib/python3.8/dist-packages/cfn_flip/__init__.py", line 55, in to_json
    data, _ = load(template)
  File "/usr/local/lib/python3.8/dist-packages/cfn_flip/__init__.py", line 34, in load
    raise e
  File "/usr/local/lib/python3.8/dist-packages/cfn_flip/__init__.py", line 27, in load
    data = load_json(template)
  File "/usr/local/lib/python3.8/dist-packages/cfn_tools/__init__.py", line 20, in load_json
    return json.loads(source, object_pairs_hook=ODict)
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Unhandled exception raised, please create an issue wit the error message at https://github.com/Skyscanner/cfripper/issues
Traceback (most recent call last):
  File "/opt/Skyscanner/cfripper/cfripper/cli.py", line 150, in cli
    process_template(template=template, resolve_parameters=resolve_parameters, **kwargs)
  File "/opt/Skyscanner/cfripper/cfripper/cli.py", line 89, in process_template
    cfmodel = get_cfmodel(template)
  File "/opt/Skyscanner/cfripper/cfripper/cli.py", line 38, in get_cfmodel
    cfmodel = pycfmodel.parse(template)
  File "/usr/local/lib/python3.8/dist-packages/pycfmodel/__init__.py", line 5, in parse
    return CFModel(**template)
TypeError: ModelMetaclass object argument after ** must be a mapping, not NoneType

**Comment by jsoucheiron** [comment]
Hi, we'd need to know more but looks like you're passing None as template.
It doesn't look like the bug is what you think it is, but it's more likely that you're not suplying the right template.

**Comment by krouser** [comment]
Hi thank you,
here is the command i ran before getting the error:

cfripper /home/stan/Desktop/Take/template.yaml /home/stan/Desktop/Take/template.json --format json --resolve --output-folder /tmp

**Comment by jsoucheiron** [comment]
Would you mind sharing the actual files (or similar files that trigger the error) so we can reproduce it?

**Comment by krouser** [comment]
[template.txt](https://github.com/Skyscanner/cfripper/files/5372652/template.txt)
i have added them.
